language: c
jobs:
  include:
    - name: "Linux GCC"
      os: linux
      compiler: gcc
    - name: "Linux Clang"
      os: linux
      compiler: clang
#    - name: "Mac OS X Clang"
#      os: osx
#      compiler: clang

addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - libavl-dev
#  homebrew:
#    packages:
#      - doxygen
#      - graphviz

script:
  - make install CC=$CC PREFIX=$(pwd)/build_result
